### ISSUE TITLE
DllNotFoundException on Application.Init for dotnet core package on MacOS X

### ISSUE THREAD

**Issue by myrup** [mono/gtk-sharp#227]
Hey.

I'm running dotnet core 2.1 preview 1. After adding the latest gtk-sharp nuget, the application fails with a DllNotFoundException on Application.Init(). Is the package not expected to be self-contained and include the necessary dependencies? If not, I am missing information on what to install on MacOSX ?

The same app runs out of the box on Raspbian :)

**Comment by hbons** [comment]
Are you building it from source? You'll need to install the Xamarin.Mac extension from the Extensions window.

**Comment by myrup** [comment]
Building what from source? All I did was add the nuget package. I have the Xamarin.Mac extension installed.

**Comment by myrup** [comment]
Any ideas? I would expect the nuget to contain dependencies (or at least warn if other actions are needed). 

I ran `brew install gtk+`, but still no luck :/

**Comment by myrup** [comment]
I release now this repo is stale and seems replaced by https://github.com/GtkSharp/GtkSharp . 
Closing.
