### ISSUE TITLE
GTK doesn't free memory.

### ISSUE THREAD

**Issue by dario279** [mono/gtk-sharp#269]
## Steps to Reproduce

1. Open project and launch

### Current Behavior
Garbage collection doesn't free memory after pop a page.

### Expected Behavior

Garbage collector should free memory after pop a page.

## On which platforms did you notice this
Linux

**Version Used**:

I tested with several of them but at the newest one (5.20.0) is happening too.

[TestHMI.zip](https://github.com/mono/mono/files/3094228/TestHMI.zip)

**Comment by Therzok** [comment]
This seems like a Xamarin.Forms bug, rather than a Mono bug.

Profiling the test sample application shows that event handlers are not removed on widget destroy.

cc @jsuarezruiz

**Comment by Therzok** [comment]
@dario279 could you please file the bug against Xamarin.Forms?

**Comment by Therzok** [comment]
In example, WPF backend does remove the event handler on dispose:
https://github.com/xamarin/Xamarin.Forms/blob/f24d6a3d6e0dd230f44273ff66e2fe04ac85a2b7/Xamarin.Forms.Platform.WPF/Renderers/ViewRenderer.cs#L322

Gtk does not:
https://github.com/xamarin/Xamarin.Forms/blob/491947606d03647124bffffcea8547e135869027/Xamarin.Forms.Platform.GTK/VisualElementRenderer.cs#L209

This is not a problem solvable _in_ gtk#

**Comment by dario279** [comment]
Thank you @Therzok . I opened a bug in Xamarin forms.

**Comment by knocte** [comment]
( https://github.com/xamarin/Xamarin.Forms/issues/5977 )
